### ISSUE TITLE
rearraging custom steps scripts

### ISSUE THREAD

**Issue by liudger** [mgear-dev/shifter#112]
When rearranging custom steps there is an error:

```
# Traceback (most recent call last):
#   File "/Users/liudger/Library/Preferences/Autodesk/maya/modules/scripts/mgear/shifter/guide.py", line 1361, in post_info
#     self.hover_info_item_entered(self.post_cs, index)
#   File "/Users/liudger/Library/Preferences/Autodesk/maya/modules/scripts/mgear/shifter/guide.py", line 1365, in hover_info_item_entered
#     info_data = self.format_info(index.data())
#   File "/Users/liudger/Library/Preferences/Autodesk/maya/modules/scripts/mgear/shifter/guide.py", line 1172, in format_info
#     data_parts = data.split("|")
# AttributeError: 'NoneType' object has no attribute 'split'
```

The script name goes blank  see image
<img width="1505" alt="error_customsteps" src="https://user-images.githubusercontent.com/4112111/113411446-0b6dac80-93b6-11eb-86ab-42d110050e47.png">

**Comment by miquelcampos** [comment]
Hello @liudger  thanks for the feedback. I will check this ASAP.
