### ISSUE TITLE
shifter guide manager: expecting new attributes

### ISSUE THREAD

**Issue by liudger** [mgear-dev/shifter#116]
guides are a bit broken after update

```
# Traceback (most recent call last):
#   File "/Users/liudger/Library/Preferences/Autodesk/maya/modules/scripts/mgear/shifter/guide_manager.py", line 103, in inspect_settings
#     wind = pyqt.showDialog(guide.guideSettings, dockable=True)
#   File "/Users/liudger/Library/Preferences/Autodesk/maya/modules/scripts/mgear/core/pyqt.py", line 158, in showDialog
#     windw = dialog()
#   File "/Users/liudger/Library/Preferences/Autodesk/maya/modules/scripts/mgear/shifter/guide.py", line 1392, in __init__
#     self.populate_controls()
#   File "/Users/liudger/Library/Preferences/Autodesk/maya/modules/scripts/mgear/shifter/guide.py", line 1503, in populate_controls
#     self.updateRgbColorWidgets(button, self.root.attr(source_attr).get(), slider)
#   File "/Applications/Autodesk/maya2020/Maya.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python2.7/site-packages/pymel/core/nodetypes.py", line 3813, in attr
#     raise e
# pymel.core.general.MayaAttributeError: Maya Attribute does not exist (or is not unique):: u'guide.L_RGB_fk'
```

**Comment by liudger** [comment]
Importing the guide fixes this. But maybe it should handle this a bit better when the guide is in the scene without this attribute?

**Comment by miquelcampos** [comment]
select the guide root and update guide command
![image](https://user-images.githubusercontent.com/1050212/121823777-5ffca480-cce2-11eb-9b8a-1fd641b0c29e.png)
when import the guide is updated automatically ;)
