### ISSUE TITLE
Duplicate Symmetry error

### ISSUE THREAD

**Issue by liudger** [mgear-dev/shifter#117]
mirror control_01 gives error

```
Checking guide
Get options
Get controllers
Get components
pupil_L0 (control_01)
Find recursive in  [ 0:00:00.047936 ]
Get parenting for: pupil_L0
Guide loaded from hierarchy in  [ 0:00:00.049241 ]
# Traceback (most recent call last):
#   File "/Users/liudger/Library/Preferences/Autodesk/maya/modules/scripts/mgear/shifter/guide_manager.py", line 48, in duplicate
#     guide.duplicate(root, sym)
#   File "/Users/liudger/Library/Preferences/Autodesk/maya/modules/scripts/mgear/shifter/guide.py", line 906, in duplicate
#     if not comp_guide.symmetrize():
#   File "/Users/liudger/Library/Preferences/Autodesk/maya/modules/scripts/mgear/shifter/component/guide.py", line 495, in symmetrize
#     if paramDef.valueType == "string":
# AttributeError: 'colorParamDef' object has no attribute 'valueType'
```

I'll try to track it down

**Comment by liudger** [comment]
Could be related to the latest RGB support commit?

**Comment by miquelcampos** [comment]
yes, it is related to that. But I think Is already fixed  https://github.com/mgear-dev/mgear4/commit/f0e1bbb3b063788b91e3967bb2e6e0872e892eea
