### ISSUE TITLE
Shifter: chain initializer UI signal error

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/shifter#48]
```
 Traceback (most recent call last):
#   File "C:\datawork\mgear_dev\mgear_dist\release\scripts\mgear\shifter\guide_manager_component.py", line 236, in draw_comp_doubleClick
#     self.draw_component()
#   File "C:\datawork\mgear_dev\mgear_dist\release\scripts\mgear\shifter\guide_manager_component.py", line 250, in draw_component
#     guide_manager.draw_comp(x.data(), parent, showUI)
#   File "C:\datawork\mgear_dev\mgear_dist\release\scripts\mgear\shifter\guide_manager.py", line 32, in draw_comp
#     guide.drawNewComponent(parent, comp_type, showUI)
#   File "C:\datawork\mgear_dev\mgear_dist\release\scripts\mgear\shifter\guide.py", line 666, in drawNewComponent
#     comp_guide.drawFromUI(parent, showUI)
#   File "C:\datawork\mgear_dev\mgear_dist\release\scripts\mgear\shifter\component\guide.py", line 362, in drawFromUI
#     if not self.modalPositions():
#   File "C:\datawork\mgear_dev\mgear_dist\release\scripts\mgear\shifter\component\guide.py", line 384, in modalPositions
#     init_window = chain_guide_initializer.exec_window()
#   File "C:\datawork\mgear_dev\mgear_dist\release\scripts\mgear\shifter\component\chain_guide_initializer.py", line 50, in exec_window
#     windw = ChainGuideInitializer()
#   File "C:\datawork\mgear_dev\mgear_dist\release\scripts\mgear\shifter\component\chain_guide_initializer.py", line 24, in __init__
#     self.setupUi(self)
#   File "C:\datawork\mgear_dev\mgear_dist\release\scripts\mgear\shifter\component\chain_guide_initializer_ui.py", line 61, in setupUi
#     QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
# AttributeError: 'module' object has no attribute 'SIGNAL'
```

**Comment by jdrese** [comment]
Thank Miquel working
