### ISSUE TITLE
renaming components will fail if the names are not unique

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/shifter#70]
if the rig is built in the scene and we edit the guide. Is possible to have name clashing. This will cause the guide to corrupt due to the name duplication:

```
# Traceback (most recent call last):
#   File "D:\Dropbox\WIP\Training\improved_deformation_and_custom_steps\env\mgear\mgear_3.2.0\scripts\mgear\shifter\guide.py", line 1024, in updateComponentName
#     guide.updateProperties(self.root, newName, newSide, newIndex)
#   File "D:\Dropbox\WIP\Training\improved_deformation_and_custom_steps\env\mgear\mgear_3.2.0\scripts\mgear\shifter\guide.py", line 916, in updateProperties
#     comp_guide = self.components[name]
# KeyError: u'chain_C0'
select -r guide|chain_C0_root ;
select -r guide|chain_C0_root|chain_C0_0_loc ;
select -r guide|chain_C0_root|chain_C0_0_loc|chain_C0_1_loc ;
select -r guide|chain_C0_root|chain_C0_0_loc|chain_C0_1_loc|chain_C0_2_loc ;
```

**Comment by jhoolmans** [comment]
There is a similar bug that doesn't have the same stack trace as listed above.
Sometimes clashing names cause the renaming to add the side index twice.

Discussion here:
http://forum.mgear-framework.com/t/component-name-changing-bug/821/3
